DROP SEQUENCE MVCBOARDSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBOARDSEQ NOCACHE;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL

);

INSERT INTO MVCBOARD VALUES(MVCBOARDSEQ.NEXTVAL,'관리자','테스트중','테스트1234','21/06/01');




SELECT*FROM MVCBOARD;